import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Outfit', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Custom accent colors
        cyan: {
          DEFAULT: "hsl(var(--cyan))",
          50: "hsl(186 100% 95%)",
          100: "hsl(186 100% 90%)",
          200: "hsl(186 100% 80%)",
          300: "hsl(186 100% 70%)",
          400: "hsl(186 100% 60%)",
          500: "hsl(186 100% 50%)",
          600: "hsl(186 100% 40%)",
          700: "hsl(186 100% 30%)",
          800: "hsl(186 100% 20%)",
          900: "hsl(186 100% 10%)",
        },
        coral: {
          DEFAULT: "hsl(var(--coral))",
          50: "hsl(0 100% 95%)",
          100: "hsl(0 100% 90%)",
          200: "hsl(0 100% 85%)",
          300: "hsl(0 100% 80%)",
          400: "hsl(0 100% 75%)",
          500: "hsl(0 100% 71%)",
          600: "hsl(0 100% 60%)",
          700: "hsl(0 100% 50%)",
          800: "hsl(0 100% 40%)",
          900: "hsl(0 100% 30%)",
        },
        purple: {
          DEFAULT: "hsl(var(--purple))",
          50: "hsl(258 90% 98%)",
          100: "hsl(258 90% 95%)",
          200: "hsl(258 90% 90%)",
          300: "hsl(258 90% 85%)",
          400: "hsl(258 90% 80%)",
          500: "hsl(258 90% 76%)",
          600: "hsl(258 90% 65%)",
          700: "hsl(258 90% 55%)",
          800: "hsl(258 90% 45%)",
          900: "hsl(258 90% 35%)",
        },
        green: {
          DEFAULT: "hsl(var(--green))",
          50: "hsl(142 76% 95%)",
          100: "hsl(142 76% 90%)",
          200: "hsl(142 76% 80%)",
          300: "hsl(142 76% 65%)",
          400: "hsl(142 76% 55%)",
          500: "hsl(142 76% 45%)",
          600: "hsl(142 76% 35%)",
          700: "hsl(142 76% 25%)",
          800: "hsl(142 76% 15%)",
          900: "hsl(142 76% 10%)",
        },
        amber: {
          DEFAULT: "hsl(var(--amber))",
          50: "hsl(38 92% 95%)",
          100: "hsl(38 92% 90%)",
          200: "hsl(38 92% 80%)",
          300: "hsl(38 92% 70%)",
          400: "hsl(38 92% 60%)",
          500: "hsl(38 92% 50%)",
          600: "hsl(38 92% 40%)",
          700: "hsl(38 92% 30%)",
          800: "hsl(38 92% 20%)",
          900: "hsl(38 92% 10%)",
        },
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
          6: "hsl(var(--chart-6))",
          7: "hsl(var(--chart-7))",
          8: "hsl(var(--chart-8))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-out": {
          from: { opacity: "1", transform: "translateY(0)" },
          to: { opacity: "0", transform: "translateY(10px)" },
        },
        "scale-in": {
          from: { transform: "scale(0.95)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
        "slide-up": {
          from: { transform: "translateY(20px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        "count-up": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "glow-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
        "fade-out": "fade-out 0.3s ease-out",
        "scale-in": "scale-in 0.3s ease-out",
        "slide-up": "slide-up 0.5s ease-out",
        "count-up": "count-up 0.3s ease-out",
        "glow-pulse": "glow-pulse 2s ease-in-out infinite",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
